MVCStoree/Components/RayonBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCStoreData;

namespace MVCStoreeWeb.Components
{
    public class RayonBarViewComponent:ViewComponent
    {
        private readonly AppDbContext context;

        public RayonBarViewComponent(
            AppDbContext context
            )
        {
            this.context = context;
        }
        public IViewComponentResult Invoke()
        {
            var model =  context.Rayons.Where(p => p.Enabled).ToList();
            return View(model);  
        
        }
    }
}

MVCStoree/Components/UserBarViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVCStoreeWeb.Components
{
   
    public class UserBarViewComponent:ViewComponent
    {
        [Authorize]
        public IViewComponentResult Invoke()
        {
              return View();
        }
    }
}
    

MVCStoree/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>  
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCStore - Güvenli Alışverişin Tek Adresi</title>   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCStoreeWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCStoreeWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">MVC Store Hakkında</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Bize Ulaşın</a>
                        </li>
                         
                    </ul>
                    <ul class="navbar-nav ms-auto">
                       @await Component.InvokeAsync("UserBar")
                    </ul>
                </div>
            </div>
        </nav>
        @await Component.InvokeAsync("RayonBar")
    </header>
    <div class="container mb-5">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top  text-muted fixed-bottom bg-white">
        <div class="container py-3">
            &copy; 2022 - MVCStoree - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(()=>{
            $('body').on('mousedown', (e) => {
                $('.category-panel').removeClass('show');
            }); 
            $('a.rayon-btn').on('click', (e) => {
                $('.category-panel').removeClass('show');
                const id =$(e.currentTarget).attr('data-category-id');
                $('div#categoryPanel_'+ id).addClass('show');
            });
          
        })
    </script>
</body>
</html>