MVCStoree/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCStoreData;
using System.Data;

namespace MVCStoreeWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Administrators")]
    public class CategoriesController : Controller
    {
        private readonly AppDbContext context;

        public CategoriesController(
           AppDbContext context
            )
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await context.Categories.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
             await Dropdowns();
            return View(new Category {Enabled=true });
        }
        [HttpPost]  
        public async Task<IActionResult> Create(Category model)
        {
            model.DateCreated= DateTime.UtcNow;
            model.Enabled = true;
            context.Categories.Add(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Kategori ekleme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await Dropdowns();
                TempData["error"] = "Aynı isimde başka bir kategori olduğundan ekleme işlemi yapılamaz ";
                return View(model);
            }
                 
        }
        [HttpGet]
        public  async Task<IActionResult> Edit(Guid id)
        {
            await Dropdowns();
            var model =  await context.Categories.FindAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category model)
        {
          
            context.Categories.Update(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Kategori güncelleme işlemi başarıyla tamamlanmıştır";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                await Dropdowns();
                TempData["error"] = "Aynı isimde başka bir kategori olduğundan güncelleme işlemi yapılamaz ";
                return View(model);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var model = await context.Categories.FindAsync(id);
            context.Categories.Remove(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Kategori silme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {

                TempData["error"] = $"{model.Name} isimli kategori bir ya da daha fazla  kayıt ile ilişkili olduğu için  silme işlemi gerçekleştirelimiyor.";

            }          
                return RedirectToAction(nameof(Index));          
        }

        private async Task Dropdowns()
        { 
            ViewBag.Rayons = new SelectList(await context.Rayons.OrderBy(p=>p.Name).ToListAsync(), "Id", "Name");
    
        }

    }

}

MVCStoree/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCStoreData;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System.Data;

namespace MVCStoreeWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrators")]


    public class ProductsController : Controller
    {
        private readonly AppDbContext context;
        private readonly IConfiguration configuration;

        public ProductsController(
           AppDbContext context,
           IConfiguration configuration
            )
        {
            this.context = context;
            this.configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            var model = await context.Products.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await Dropdowns();
            return View(new Product { Enabled = true });
        }
        [HttpPost]
        public async Task<IActionResult> Create(Product model)
        {
            model.DateCreated= DateTime.UtcNow;
            model.Enabled = true;
            model.Price = decimal.Parse(model.PriceText);
            model.DiscountedPrice = model.DiscountedPriceText != null ? decimal.Parse(model.DiscountedPriceText) : null;
            var categories = await context.Categories.Where(p => model.CategoryIds.Any(q => q == p.Id)).ToListAsync();

            if (model.Images is not null)
            {
                foreach (var file in model.Images)
                {
                    var image = await Image.LoadAsync(file.OpenReadStream());
                    image.Mutate(p => {
                        p.Resize(
                            configuration.GetValue<int>("DefaultImageSize:Width"),
                            configuration.GetValue<int>("DefaultImageSize:Height"));
                    
                    });

                    using var ms = new MemoryStream();
                    await image.SaveAsJpegAsync(ms);
                     
                    model.ProductImages.Add(new ProductImage
                    {
                        DateCreated = DateTime.UtcNow,
                        Enabled = true,
                        Image = ms.ToArray()
                }); 
                }
            } 
            context.Products.Add(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Ürün ekleme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await Dropdowns();

                TempData["error"] = "Aynı isimde başka bir ürün olduğundan ekleme işlemi yapılamaz ";
                return View(model);
            }
                 
        }
        [HttpGet]
        public  async Task<IActionResult> Edit(Guid id)
        {
            await Dropdowns();

            var model =  await context.Products.FindAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product model)
        {
          
            context.Products.Update(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Ürün güncelleme işlemi başarıyla tamamlanmıştır";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                await Dropdowns();

                TempData["error"] = "Aynı isimde başka bir ürün olduğundan güncelleme işlemi yapılamaz ";
                return View(model);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var model = await context.Products.FindAsync(id);
            context.Products.Remove(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Ürün silme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {

                TempData["error"] = $"{model.Name} isimli ürün bir ya da daha fazla  kayıt ile ilişkili olduğu için  silme işlemi gerçekleştirilemiyor.";

            }          
                return RedirectToAction(nameof(Index));          
        }
        private async Task Dropdowns()
        {
            ViewBag.Categories = new SelectList(await context.Categories.Select(p=> new {p.Id, p.Name, RayonName = p.Rayon!.Name }).OrderBy(p=>p.Name).ToListAsync(), "Id", "Name", null,"RayonName");

        }
    }

}

MVCStoree/Areas/Admin/Controllers/RayonsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCStoreData;
using System.Data;

namespace MVCStoreeWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrators,ProductAdministrators")]

    public class RayonsController : Controller
    {
        private readonly AppDbContext context;

        public RayonsController(
           AppDbContext context
            )
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await context.Rayons.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Rayon {Enabled=true });
        }
        [HttpPost]
        public async Task<IActionResult> Create(Rayon model)
        {
            model.DateCreated= DateTime.UtcNow;
            model.Enabled = true;

            context.Rayons.Add(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Reyon ekleme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["error"] = "Beklenmedik hata, daha sonra tekrar deneyiniz! ";
                return View(model);
            }
                 
        }
        [HttpGet]
        public  async Task<IActionResult> Edit(Guid id)
        {
            var model =  await context.Rayons.FindAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Rayon model)
        {
          
            context.Rayons.Update(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Reyon güncelleme işlemi başarıyla tamamlanmıştır";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                TempData["error"] = "Aynı isimde başka bir reyon olduğundan güncelleme işlemi yapılamaz ";
                return View(model);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var model = await context.Rayons.FindAsync(id);
            context.Rayons.Remove(model);
            try
            {
                await context.SaveChangesAsync();
                TempData["success"] = "Reyon silme işlemi başarıyla tamamlanmıştır";

                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {

                TempData["error"] = $"{model.Name} isimli reyon bir ya da daha fazla  kayıt ile ilişkili olduğu için  silme işlemi gerçekleştirelimiyor.";

            }          
                return RedirectToAction(nameof(Index));          
        }
    }

}

MVCStoree/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/admin.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

  

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-shopping-cart"></i>
                </div>
                <div class="sidebar-brand-text mx-3">
                    <b>MVC</b>Store Admin
                </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Heading -->
            <div class="sidebar-heading">
                Tanımlamalar
            </div>
            <li class="nav-item">
                <a class="nav-link"  asp-controller="Rayons" asp-action="Index">
                    <i class="fas fa-fw fa-cubes"></i>
                    <span>Reyon Tanımları</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link"  asp-controller="Categories" asp-action="Index">
                    <i class="fas fa-fw fa-cube"></i>
                    <span>Kategori Tanımları</span>
                </a>
            </li>
              <li class="nav-item ">
                <a class="nav-link"  asp-controller="Products" asp-action="Index">
                    <i class="fas fa-fw fa-gift"></i>
                    <span>Ürün Tanımları</span>
                </a>
            </li>
            <div class="sidebar-heading">
                Sipariş -  Üye
            </div>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Orders" asp-action="Index">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                    <span>Sipariş Tanımları</span>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Members" asp-action="Index">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                    <span>Üyeler</span>
                </a>
            </li>
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fa fa-store"></i>
                            
                                Mağazaya Git</a>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <i class="fa fa-user mr-2"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                   Çıkış
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800"> @ViewData["Title"]
                    </h1>
                    @if (TempData["success"] is not  null )
                    {
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <i class="fa fa-check"></i> @TempData["success"]
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                    @if (TempData["error"] is not null)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <i class="fa fa-exclamation-triangle"></i> @TempData["error"]
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy;@DateTime.Today.Year - MVCStore -Tüm Hakları Saklıdır</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">İptal</button>

                    <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Logout">Çıkış
                        <i class="fa fa-power-off"></i>
                    
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.1/js/bootstrap.bundle.min.js" integrity="sha512-1TK4hjCY5+E9H3r5+05bEGbKGyK506WaDPfPe1s/ihwRjr6OtL43zJLzOFQ+/zciONEd+sp7LwrfOCnyukPSsg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" integrity="sha512-0QbL0ph8Tc8g5bLhfVzSqxe9GERORsKhIn1IrpxDAgUsbBGz/V7iSav2zzW325XGd1OMLdL4UiqRJj702IeqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/admin/startbootstrap-sb-admin-2/js/sb-admin-2.min.js"></script>  
    @await RenderSectionAsync("scripts", false)
</body>

</html>